/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
public class Allowance extends AbstractEntity {

    @Basic
    @NotNull(message = "Allowance name must be set")
    private String allowanceName;

    @Basic
    @NotNull(message = "Allowance type must be set")
    private String allowanceType;

    @Basic
    private boolean isTaxable;

    public String getAllowanceName() {
        return this.allowanceName;
    }

    public void setAllowanceName(String allowanceName) {
        this.allowanceName = allowanceName;
    }

    public String getAllowanceType() {
        return this.allowanceType;
    }

    public void setAllowanceType(String allowanceType) {
        this.allowanceType = allowanceType;
    }

    public boolean isIsTaxable() {
        return this.isTaxable;
    }

    public void setIsTaxable(boolean isTaxable) {
        this.isTaxable = isTaxable;
    }

}