/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
public class Department extends AbstractEntity {

    @Basic
    @NotNull
    private String name;

    @OneToMany(targetEntity = Employee.class, mappedBy = "department")
    private Set<Employee> employees = new HashSet();

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

}