/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

/**
 * @author pedantic
 */
@Entity
public class EmployeeBank extends AbstractEntity {

    @Basic
    private String accountNumber;

    @Basic
    private String branch;

    @Basic
    private String swift;

    @OneToOne(targetEntity = Bank.class)
    private Bank bank;

    @OneToOne(targetEntity = Employee.class)
    private Employee employee;

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getBranch() {
        return this.branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getSwift() {
        return this.swift;
    }

    public void setSwift(String swift) {
        this.swift = swift;
    }

    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

}