/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * @author pedantic
 */
@Entity
public class EmployeeAllowance extends AbstractEntity {

    @Basic
    private BigDecimal allowanceAmount;

    @OneToOne(targetEntity = Allowance.class)
    private Allowance allowance;

    @ManyToOne(targetEntity = Employee.class)
    private Employee employee;

    public BigDecimal getAllowanceAmount() {
        return this.allowanceAmount;
    }

    public void setAllowanceAmount(BigDecimal allowanceAmount) {
        this.allowanceAmount = allowanceAmount;
    }

    public Allowance getAllowance() {
        return this.allowance;
    }

    public void setAllowance(Allowance allowance) {
        this.allowance = allowance;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

}