/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.math.BigDecimal;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
@NamedQueries(@NamedQuery(name=EmployeeAllowance.GET_EMPLOYEE_ALLOWANCES,
        query = "select eA from EmployeeAllowance eA where eA.employee = :employee"))
public class EmployeeAllowance extends AbstractEntity {

    public static final String GET_EMPLOYEE_ALLOWANCES = "getAllEmployeeAllowances";
    @Basic
    @NotNull(message = "Allowance amount must be set")
    private BigDecimal allowanceAmount;

    @OneToOne(targetEntity = Allowance.class)
    private Allowance allowance;

    @ManyToOne(targetEntity = Employee.class)
    private Employee employee;

    public BigDecimal getAllowanceAmount() {
        return this.allowanceAmount;
    }

    public void setAllowanceAmount(BigDecimal allowanceAmount) {
        this.allowanceAmount = allowanceAmount;
    }

    public Allowance getAllowance() {
        return this.allowance;
    }

    public void setAllowance(Allowance allowance) {
        this.allowance = allowance;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

}