/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
public class Loan extends AbstractEntity {

    @Basic
    @NotNull(message = "Name is required")
    private String loanName;

    @Basic
    private boolean isRecurrent;

    public String getLoanName() {
        return this.loanName;
    }

    public void setLoanName(String loanName) {
        this.loanName = loanName;
    }

    public boolean isIsRecurrent() {
        return this.isRecurrent;
    }

    public void setIsRecurrent(boolean isRecurrent) {
        this.isRecurrent = isRecurrent;
    }

}