/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
public class SocialSecurityRates extends AbstractEntity {

    @Basic
    @NotNull(message = "Employee rate must be set")
    private BigDecimal employeeContributionRate;

    @Basic
    @NotNull(message = "Employer rate must be set")
    private BigDecimal employerContributionRate;

    public BigDecimal getEmployeeContributionRate() {
        return this.employeeContributionRate;
    }

    public void setEmployeeContributionRate(BigDecimal employeeContributionRate) {
        this.employeeContributionRate = employeeContributionRate;
    }

    public BigDecimal getEmployerContributionRate() {
        return this.employerContributionRate;
    }

    public void setEmployerContributionRate(BigDecimal employerContributionRate) {
        this.employerContributionRate = employerContributionRate;
    }

}