/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
public class Tax extends AbstractEntity {

    @Basic
    @NotNull(message = "Tax rate must be set")
    private BigDecimal taxRate;

    public BigDecimal getTaxRate() {
        return this.taxRate;
    }

    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

}