/**
 * This file was generated by the Jeddict
 */
package com.pedantic.entities;

import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.validation.constraints.NotNull;

/**
 * @author pedantic
 */
@Entity
@NamedQuery(name = Tax.GET_TAXES, query = "select t from Tax t")
public class Tax extends AbstractEntity {
    public static final String GET_TAXES = "getAllTaxes";
    @Basic
    @NotNull(message = "Tax rate must be set")
    private BigDecimal taxRate;

    public BigDecimal getTaxRate() {
        return this.taxRate;
    }

    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

}